# Generated by Django 4.2.5 on 2023-09-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='movie',
        ),
    ]
