# Generated by Django 4.2.5 on 2023-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_post_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
