# Generated by Django 4.2.5 on 2023-09-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_movie_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='like_count',
        ),
    ]
